// Package abaxoapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package abaxoapi

import (
	"time"
)

// Defines values for APICapabilityCapability.
const (
	APICapabilityCapabilityQueryEquipment              APICapabilityCapability = "query-equipment"
	APICapabilityCapabilityQueryEquipmentLocations     APICapabilityCapability = "query-equipment-locations"
	APICapabilityCapabilityQueryPeople                 APICapabilityCapability = "query-people"
	APICapabilityCapabilityQueryTripExpenseAndExtra    APICapabilityCapability = "query-trip-expense-and-extra"
	APICapabilityCapabilityQueryTripRoute              APICapabilityCapability = "query-trip-route"
	APICapabilityCapabilityQueryTrips                  APICapabilityCapability = "query-trips"
	APICapabilityCapabilityQueryVehicleDriveStates     APICapabilityCapability = "query-vehicle-drive-states"
	APICapabilityCapabilityQueryVehicleLocationHistory APICapabilityCapability = "query-vehicle-location-history"
	APICapabilityCapabilityQueryVehicleLocations       APICapabilityCapability = "query-vehicle-locations"
	APICapabilityCapabilityQueryVehicles               APICapabilityCapability = "query-vehicles"
)

// Defines values for DriveStateValue.
const (
	DriveStateValueIdling  DriveStateValue = "Idling"
	DriveStateValueMoving  DriveStateValue = "Moving"
	DriveStateValueParked  DriveStateValue = "Parked"
	DriveStateValueUnknown DriveStateValue = "Unknown"
)

// Defines values for FuelType.
const (
	FuelTypeDiesel       FuelType = "Diesel"
	FuelTypeDieselHybrid FuelType = "DieselHybrid"
	FuelTypeElectricity  FuelType = "Electricity"
	FuelTypeLpg          FuelType = "Lpg"
	FuelTypePetrol       FuelType = "Petrol"
	FuelTypePetrolHybrid FuelType = "PetrolHybrid"
	FuelTypeUnknown      FuelType = "Unknown"
)

// Defines values for InputType.
const (
	InputTypeBlue   InputType = "Blue"
	InputTypeWhite  InputType = "White"
	InputTypeYellow InputType = "Yellow"
)

// Defines values for SignalSource.
const (
	SignalSourceGps SignalSource = "Gps"
	SignalSourceGsm SignalSource = "Gsm"
)

// Defines values for TripCommercialClass.
const (
	TripCommercialClassBusinessTrip TripCommercialClass = "BusinessTrip"
	TripCommercialClassCommute      TripCommercialClass = "Commute"
	TripCommercialClassPrivateTrip  TripCommercialClass = "PrivateTrip"
	TripCommercialClassUnknown      TripCommercialClass = "Unknown"
)

// Defines values for TripSource.
const (
	TripSourceAutomatic TripSource = "Automatic"
	TripSourceManual    TripSource = "Manual"
)

// Defines values for UnitHealth.
const (
	UnitHealthDegraded  UnitHealth = "Degraded"
	UnitHealthHealthy   UnitHealth = "Healthy"
	UnitHealthUnhealthy UnitHealth = "Unhealthy"
	UnitHealthUnknown   UnitHealth = "Unknown"
)

// Defines values for UnitStatus.
const (
	UnitStatusActive      UnitStatus = "Active"
	UnitStatusDeactivated UnitStatus = "Deactivated"
	UnitStatusUnknown     UnitStatus = "Unknown"
)

// Defines values for UnitTypeParameter.
const (
	UnitTypeParameterMini UnitTypeParameter = "Mini"
)

// Defines values for UsageLogInputType.
const (
	UsageLogInputTypeBlue   UsageLogInputType = "Blue"
	UsageLogInputTypeWhite  UsageLogInputType = "White"
	UsageLogInputTypeYellow UsageLogInputType = "Yellow"
)

// Defines values for VehicleCommercialClass.
const (
	VehicleCommercialClassCommercial               VehicleCommercialClass = "Commercial"
	VehicleCommercialClassCommercialWithPrivateUse VehicleCommercialClass = "CommercialWithPrivateUse"
	VehicleCommercialClassCompany                  VehicleCommercialClass = "Company"
	VehicleCommercialClassPrivate                  VehicleCommercialClass = "Private"
	VehicleCommercialClassUnknown                  VehicleCommercialClass = "Unknown"
)

// APICapability defines model for ApiCapability.
type APICapability struct {
	Capability *APICapabilityCapability `json:"capability,omitempty"`
}

// APICapabilityCapability defines model for APICapability.Capability.
type APICapabilityCapability string

// CompanyAddress defines model for CompanyAddress.
type CompanyAddress struct {
	City       *string `json:"city"`
	Country    *string `json:"country"`
	PostalCode *string `json:"postalCode"`
	Street     *string `json:"street"`
}

// CompanyInfo defines model for CompanyInfo.
type CompanyInfo struct {
	Address               *CompanyAddress `json:"address,omitempty"`
	CompanyName           *string         `json:"companyName"`
	EmailContact          *string         `json:"emailContact"`
	PhoneNumber           *string         `json:"phoneNumber"`
	TaxRegistrationNumber *string         `json:"taxRegistrationNumber"`
}

// ContactInformation defines model for ContactInformation.
type ContactInformation struct {
	Email       *string `json:"email"`
	PhoneNumber *string `json:"phone_number"`
}

// DriveState defines model for DriveState.
type DriveState struct {
	// Timestamp in UTC time
	Timestamp *time.Time       `json:"timestamp"`
	Value     *DriveStateValue `json:"value,omitempty"`
}

// DriveStateValue defines model for DriveStateValue.
type DriveStateValue string

// Driver defines model for Driver.
type Driver struct {
	Email       *string `json:"email"`
	ExternalID  *string `json:"external_id"`
	ID          *string `json:"id,omitempty"`
	Name        *string `json:"name"`
	PhoneNumber *string `json:"phone_number"`
}

// DrivingBehaviourDriverScore defines model for DrivingBehaviourDriverScore.
type DrivingBehaviourDriverScore struct {
	DriverID   *string                `json:"driver_id,omitempty"`
	DriverName *string                `json:"driver_name,omitempty"`
	Score      *DrivingBehaviourScore `json:"score,omitempty"`
}

// DrivingBehaviourScore defines model for DrivingBehaviourScore.
type DrivingBehaviourScore struct {
	AccelerationScore   *int `json:"acceleration_score,omitempty"`
	BrakingScore        *int `json:"braking_score,omitempty"`
	IdlingScore         *int `json:"idling_score,omitempty"`
	LeftCorneringScore  *int `json:"left_cornering_score,omitempty"`
	RightCorneringScore *int `json:"right_cornering_Score,omitempty"`
	TotalScore          *int `json:"total_score,omitempty"`
}

// Equipment defines model for Equipment.
type Equipment struct {
	Alias                 *string         `json:"alias"`
	AssetID               *string         `json:"asset_id"`
	EquipmentIdentifier   *string         `json:"equipment_identifier"`
	ID                    *string         `json:"id,omitempty"`
	InitialOperatingHours *OperatingHours `json:"initial_operating_hours,omitempty"`
	Location              *Location       `json:"location,omitempty"`
	Model                 *Model          `json:"model,omitempty"`
	Notes                 *string         `json:"notes"`
	OperatingHours        *OperatingHours `json:"operating_hours,omitempty"`
	Organization          *Organization   `json:"organization,omitempty"`
	Pin                   *string         `json:"pin"`

	// RegisteredAt in UTC time
	RegisteredAt *time.Time     `json:"registered_at"`
	SerialNumber *string        `json:"serial_number"`
	Unit         *EquipmentUnit `json:"unit,omitempty"`
}

// EquipmentLocation defines model for EquipmentLocation.
type EquipmentLocation struct {
	ID       *string   `json:"id,omitempty"`
	Location *Location `json:"location,omitempty"`
}

// EquipmentUnit defines model for EquipmentUnit.
type EquipmentUnit struct {
	Health       *UnitHealth `json:"health,omitempty"`
	ID           *string     `json:"id,omitempty"`
	RelayUnit    *RelayUnit  `json:"relay_unit,omitempty"`
	SerialNumber *string     `json:"serial_number"`
	Status       *UnitStatus `json:"status,omitempty"`
	Type         *string     `json:"type,omitempty"`
}

// EquipmentV2 defines model for EquipmentV2.
type EquipmentV2 struct {
	Alias               *string       `json:"alias"`
	AssetID             *string       `json:"asset_id"`
	EquipmentIdentifier *string       `json:"equipment_identifier"`
	ID                  *string       `json:"id,omitempty"`
	Inputs              []Input       `json:"inputs,omitempty"`
	Location            *Location     `json:"location,omitempty"`
	Model               *Model        `json:"model,omitempty"`
	Notes               *string       `json:"notes"`
	Organization        *Organization `json:"organization,omitempty"`
	Pin                 *string       `json:"pin"`

	// RegisteredAt in UTC time
	RegisteredAt *time.Time     `json:"registered_at"`
	SerialNumber *string        `json:"serial_number"`
	Unit         *EquipmentUnit `json:"unit,omitempty"`
}

// Expense defines model for Expense.
type Expense struct {
	EasyParkCorporate *float64 `json:"easy_park_corporate"`
	EasyParkPrivate   *float64 `json:"easy_park_private"`
	Ferry             *float64 `json:"ferry"`
	Parking           *float64 `json:"parking"`
	TollCharge        *float64 `json:"toll_charge"`
	TollRoadAdmin     *float64 `json:"toll_road_admin"`
}

// ExpenseAndExtra defines model for ExpenseAndExtra.
type ExpenseAndExtra struct {
	Expense *Expense `json:"expense,omitempty"`
	Extra   *Extra   `json:"extra,omitempty"`
	TripID  *string  `json:"trip_id,omitempty"`
}

// Extra defines model for Extra.
type Extra struct {
	DistanceWithBadRoadInKm   *float64 `json:"distance_with_bad_road_in_km"`
	DistanceWithCanteenInKm   *float64 `json:"distance_with_canteen_in_km"`
	DistanceWithCaravanInKm   *float64 `json:"distance_with_caravan_in_km"`
	DistanceWithDogInKm       *float64 `json:"distance_with_dog_in_km"`
	DistanceWithHeavyLoadInKm *float64 `json:"distance_with_heavy_load_in_km"`
	DistanceWithPassengerInKm *float64 `json:"distance_with_passenger_in_km"`
	DistanceWithTrailerInKm   *float64 `json:"distance_with_trailer_in_km"`
	PassengerName             *string  `json:"passenger_name"`
}

// FuelType defines model for FuelType.
type FuelType string

// Input defines model for Input.
type Input struct {
	AccumulatedUsageTimeLastServiceHours *int32     `json:"accumulated_usage_time_last_service_hours,omitempty"`
	AccumulatedUsageTimeSeconds          *int32     `json:"accumulated_usage_time_seconds,omitempty"`
	InitialUsageTimeHours                *int32     `json:"initial_usage_time_hours,omitempty"`
	Name                                 *string    `json:"name,omitempty"`
	ServiceAlertLimitHours               *int32     `json:"service_alert_limit_hours,omitempty"`
	ServiceIntervalHours                 *int32     `json:"service_interval_hours,omitempty"`
	Type                                 *InputType `json:"type,omitempty"`
	UsageTimeSinceLastServiceHours       *int32     `json:"usage_time_since_last_service_hours,omitempty"`
}

// InputType defines model for InputType.
type InputType string

// LicensePlate defines model for LicensePlate.
type LicensePlate struct {
	Number           *string    `json:"number,omitempty"`
	RegistrationDate *time.Time `json:"registration_date"`
}

// Location defines model for Location.
type Location struct {
	// AccuracyRadius meters
	AccuracyRadius *float32      `json:"accuracy_radius"`
	Course         *int32        `json:"course"`
	InMovement     *bool         `json:"in_movement"`
	Latitude       *float32      `json:"latitude,omitempty"`
	Longitude      *float32      `json:"longitude,omitempty"`
	SignalSource   *SignalSource `json:"signal_source,omitempty"`

	// Speed kilometers per hour, in some cases speed will not be returned due to privacy regulations
	Speed *float32 `json:"speed"`

	// Timestamp in UTC time
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// LocationPoint defines model for LocationPoint.
type LocationPoint struct {
	// AccuracyRadius meters
	AccuracyRadius *float32      `json:"accuracy_radius"`
	Latitude       *float32      `json:"latitude,omitempty"`
	Longitude      *float32      `json:"longitude,omitempty"`
	SignalSource   *SignalSource `json:"signal_source,omitempty"`

	// Timestamp in UTC time
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// Manufacturer defines model for Manufacturer.
type Manufacturer struct {
	Name *string `json:"name,omitempty"`
}

// Model defines model for Model.
type Model struct {
	Name *string `json:"name,omitempty"`
}

// OdometerReading defines model for OdometerReading.
type OdometerReading struct {
	// Timestamp in UTC time
	Timestamp *time.Time `json:"timestamp"`

	// Value meters
	Value *float32 `json:"value,omitempty"`
}

// OperatingHours defines model for OperatingHours.
type OperatingHours struct {
	Hours      *float64 `json:"hours,omitempty"`
	UnitDriven *bool    `json:"unit_driven,omitempty"`
}

// Organization defines model for Organization.
type Organization struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

// Person defines model for Person.
type Person struct {
	Contact    *ContactInformation `json:"contact,omitempty"`
	ExternalID *string             `json:"external_id"`
	ID         *string             `json:"id,omitempty"`
	Name       *string             `json:"name"`
}

// RelayUnit defines model for RelayUnit.
type RelayUnit struct {
	Alias        *string `json:"alias"`
	ID           *string `json:"id,omitempty"`
	SerialNumber *string `json:"serial_number"`
	UnitType     *string `json:"unit_type,omitempty"`
}

// SensorData defines model for SensorData.
type SensorData struct {
	ID         *string         `json:"id,omitempty"`
	SensorData []SensorReading `json:"sensor_data,omitempty"`
}

// SensorReading defines model for SensorReading.
type SensorReading struct {
	BoolValue    *bool    `json:"bool_value"`
	IntValue     *int64   `json:"int_value"`
	NumericValue *float64 `json:"numeric_value"`
	SensorID     *string  `json:"sensor_id,omitempty"`
	StringValue  *string  `json:"string_value,omitempty"`

	// Timestamp in UTC time
	Timestamp *time.Time `json:"timestamp"`
	Unit      *string    `json:"unit,omitempty"`
}

// SignalSource defines model for SignalSource.
type SignalSource string

// Trip defines model for Trip.
type Trip struct {
	CommercialClass *TripCommercialClass `json:"commercial_class,omitempty"`

	// Distance meters
	Distance *int    `json:"distance"`
	Driver   *Driver `json:"driver,omitempty"`

	// Duration seconds
	Duration *int         `json:"duration"`
	Finish   *TripPoint   `json:"finish,omitempty"`
	ID       *string      `json:"id,omitempty"`
	Notes    *string      `json:"notes"`
	Purpose  *string      `json:"purpose"`
	Source   *TripSource  `json:"source,omitempty"`
	Start    *TripPoint   `json:"start,omitempty"`
	Vehicle  *TripVehicle `json:"vehicle,omitempty"`
}

// TripCommercialClass defines model for TripCommercialClass.
type TripCommercialClass string

// TripOdometerReading defines model for TripOdometerReading.
type TripOdometerReading struct {
	TripFinish *OdometerReading `json:"trip_finish,omitempty"`
	TripID     *string          `json:"trip_id,omitempty"`
	TripStart  *OdometerReading `json:"trip_start,omitempty"`
}

// TripPoint defines model for TripPoint.
type TripPoint struct {
	// Address in some cases address will not have house number due to privacy regulations
	Address  *string        `json:"address"`
	Location *LocationPoint `json:"location,omitempty"`
}

// TripRoute defines model for TripRoute.
type TripRoute struct {
	Locations []TripRouteLocation `json:"locations,omitempty"`
	TripID    *string             `json:"trip_id,omitempty"`
}

// TripRouteLocation defines model for TripRouteLocation.
type TripRouteLocation struct {
	Course       *int32        `json:"course"`
	InMovement   *bool         `json:"in_movement"`
	Latitude     *float32      `json:"latitude,omitempty"`
	Longitude    *float32      `json:"longitude,omitempty"`
	SignalSource *SignalSource `json:"signal_source,omitempty"`

	// Speed kilometers per hour, in some cases speed will not be returned due to privacy regulations
	Speed *float32 `json:"speed"`

	// Timestamp in UTC time
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// TripSource defines model for TripSource.
type TripSource string

// TripVehicle defines model for TripVehicle.
type TripVehicle struct {
	Alias           *string                 `json:"alias,omitempty"`
	CommercialClass *VehicleCommercialClass `json:"commercial_class,omitempty"`
	ID              *string                 `json:"id,omitempty"`
}

// UnitHealth defines model for UnitHealth.
type UnitHealth string

// UnitStatus defines model for UnitStatus.
type UnitStatus string

// UnitTypeParameter defines model for UnitTypeParameter.
type UnitTypeParameter string

// UsageLog defines model for UsageLog.
type UsageLog struct {
	Address *string `json:"address,omitempty"`

	// EndTime in UTC time
	EndTime     *time.Time         `json:"end_time,omitempty"`
	EquipmentID *string            `json:"equipment_id,omitempty"`
	InputType   *UsageLogInputType `json:"input_type,omitempty"`

	// StartTime in UTC time
	StartTime  *time.Time `json:"start_time,omitempty"`
	Usage      *int64     `json:"usage,omitempty"`
	UsageLogID *int64     `json:"usage_log_id,omitempty"`
}

// UsageLogInputType defines model for UsageLog.InputType.
type UsageLogInputType string

// Vehicle defines model for Vehicle.
type Vehicle struct {
	Alias   *string `json:"alias,omitempty"`
	AssetID *string `json:"asset_id"`

	// Co2Emissions g/km
	Co2Emissions    *float32                `json:"co2_emissions"`
	Color           *string                 `json:"color"`
	CommercialClass *VehicleCommercialClass `json:"commercial_class,omitempty"`
	Driver          *Driver                 `json:"driver,omitempty"`

	// EngineSize cubic centimeters (cc)
	EngineSize *int `json:"engine_size"`

	// FuelConsumption For electric vehicles: kWh/100km, for UK: miles per gallon, for Norway and Sweden: liters per Scandinavian mile, otherwise: liters per 100km
	FuelConsumption *float32         `json:"fuel_consumption"`
	FuelType        *FuelType        `json:"fuel_type,omitempty"`
	ID              *string          `json:"id,omitempty"`
	LicensePlate    *LicensePlate    `json:"license_plate,omitempty"`
	Location        *Location        `json:"location,omitempty"`
	Manufacturer    *Manufacturer    `json:"manufacturer,omitempty"`
	Model           *Model           `json:"model,omitempty"`
	Notes           *string          `json:"notes"`
	Odometer        *OdometerReading `json:"odometer,omitempty"`
	Organization    *Organization    `json:"organization,omitempty"`

	// RegisteredAt in UTC time
	RegisteredAt *time.Time   `json:"registered_at"`
	Unit         *VehicleUnit `json:"unit,omitempty"`
	VIN          *string      `json:"vin"`
}

// VehicleCommercialClass defines model for VehicleCommercialClass.
type VehicleCommercialClass string

// VehicleDriveState defines model for VehicleDriveState.
type VehicleDriveState struct {
	DriveState *DriveState `json:"drive_state,omitempty"`
	ID         *string     `json:"id,omitempty"`
}

// VehicleLocation defines model for VehicleLocation.
type VehicleLocation struct {
	ID       *string   `json:"id,omitempty"`
	Location *Location `json:"location,omitempty"`
}

// VehicleRecentLocations defines model for VehicleRecentLocations.
type VehicleRecentLocations struct {
	ID        *string    `json:"id,omitempty"`
	Locations []Location `json:"locations,omitempty"`
}

// VehicleUnit defines model for VehicleUnit.
type VehicleUnit struct {
	Health       *UnitHealth `json:"health,omitempty"`
	ID           *string     `json:"id,omitempty"`
	SerialNumber *string     `json:"serial_number"`
	Status       *UnitStatus `json:"status,omitempty"`
	Type         *string     `json:"type,omitempty"`
}
